version: "3.9"
services:
  app:
    image: ghcr.io/archessmn/checkout:latest
    ports:
      - "3006:3000"
    env_file:
      - .env.local

networks:
  default:
    external: true
    name: checkout_default
