version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
        PUBLIC_URL: "https://checkout.theshrine.net"
    working_dir: /app
    ports:
      - "3006:3000"
    image: t3-app
    env_file:
      - .env.local
