export const metadata = {
  title: "Checkout API Docs",
  description:
    "Generated by spending too much time figuring out how to automate it",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.11.7/swagger-ui.css"
          integrity="sha512-ycnSmYVRkrg4YI0l+PGQy8hjupRbZElWaFMp9wO11Gy2SsCVNexEyNF0GFPkOY97zdkXgO7fTY7TcWJamvz2gw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
